### ISSUE TITLE
Create phinx migration files from existing database tables

### ISSUE THREAD

**Issue by faizalmansor** [cakephp/phinx#1610] opened 2019-09-06 02:24 UTC
Is there a plugin for this? If not, how would I go about making one? Any ideas would be greatly appreciated.

**Comment by MasterOdin** [comment] 2019-09-06 02:54
For MySQL 5.7+, there exists https://github.com/odan/phinx-migrations-generator. Not sure if there's anything for the other database types.

**Comment by dereuromark** [comment] 2020-04-11 06:24
Duplicate of https://github.com/cakephp/phinx/issues/820

**Closed by dereuromark** 2020-04-11 06:24 UTC
Labels: support
