### ISSUE TITLE
v1.3.0 Invalid version migrate command

### ISSUE THREAD

**Issue by xpnn** [cakephp/phinx#2121] opened 2022-10-11 01:52 UTC
In robmorgan/phinx: ^ 0.13.0, running the phinx migrate - e development command is invalid. 
My environment is php8.0. After troubleshooting many problems, I found that it is located 
in`/vendor/robmorgan/phinx/src/Hinx/Console/Command/Migrate` There is a logic bug in line 66 of the php file. 
The obtained $version parameter is cast to the int type, causing the migration to fail to execute

```
// In file `/vendor/robmorgan/phinx/src/Hinx/Console/Command/Migrate` , line 66

protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $this->bootstrap($input, $output);

       // Bug location.
        $version = (int)$input->getOption('target');
        /** @var string|null $environment */
        $environment = $input->getOption('environment');
        $date = $input->getOption('date');
        $fake = (bool)$input->getOption('fake');
       .......

        return self::CODE_SUCCESS;
    }
```

**Comment by MasterOdin** [comment] 2022-10-11 04:53
Duplicate of #2112, was fixed by #2115, and released just now as part of [0.13.1](https://github.com/cakephp/phinx/releases/tag/0.13.1).

**Closed as completed by MasterOdin** 2022-10-11 04:53 UTC
