### ISSUE TITLE
dropColumn fails on SQLite databases if the type is enum

### ISSUE THREAD

**Issue by betterphp** [cakephp/phinx#1086] opened 2017-05-05 13:15 UTC
Removing a column for SQLite works by creating a new table without the requested column then dropping it and renaming the new table to replace it.

If the column is an enum with more than one value option then this fails as the regex to remove the entry from the create table statement does not handle commas correctly.
~~~
[InvalidArgumentException]
The specified column doesn't exist: type

Exception trace:
() at ./vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SQLiteAdapter.php:489
Phinx\Db\Adapter\SQLiteAdapter->dropColumn() at ./db/migrations/20170505100124_split_affects_fields.php:22
SplitAffectsFields->up() at ./vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php:125
Phinx\Migration\Manager\Environment->executeMigration() at ./vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:366
Phinx\Migration\Manager->executeMigration() at ./vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:342
Phinx\Migration\Manager->migrate() at ./vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php:113
Phinx\Console\Command\Migrate->execute() at ./vendor/symfony/console/Command/Command.php:264
Symfony\Component\Console\Command\Command->run() at ./vendor/symfony/console/Application.php:835
Symfony\Component\Console\Application->doRunCommand() at ./vendor/symfony/console/Application.php:200
Symfony\Component\Console\Application->doRun() at ./vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php:83
Phinx\Console\PhinxApplication->doRun() at ./vendor/symfony/console/Application.php:124
Symfony\Component\Console\Application->run() at ./vendor/robmorgan/phinx/bin/phinx:28
~~~
The message is confusing but it comes from the table essentially not existing due to failed queries.

I've attached ([phinx-sqlite-bug-demo.zip](https://github.com/robmorgan/phinx/files/979114/phinx-sqlite-bug-demo.zip)) migrations that cause this error, to reproduce it extract the zip then do
~~~bash
composer install
./vendor/bin/phinx migrate
~~~
from the folder.

A workaround I'm using for now is to change the column to a TEXT field before removing it so that the regex doesn't create invalid SQL.

**Comment by pr0ggy** [comment] 2017-05-15 19:08
Taking a look at this now, working on a fix

**Comment by nebez** [comment] 2017-07-07 17:37
Having the same issue. Waiting on the PR to be merged. In the meantime, I've merged your code into my fork. Will report back if it fixes the issue.

**Comment by tariquesani** [comment] 2017-07-11 03:56
@pr0ggy Some changes were requested for your PR also it is failing some tests. Would you be interested in fixing those?

**Comment by pr0ggy** [comment] 2017-07-11 12:39
Yes, I apologize for the delay...life been a bit crazy here lately.  I plan on taking a look at the needed changes either tonight or tomorrow at latest.

**Closed** 2017-07-12 17:38 UTC

**Comment by nebez** [comment] 2017-07-13 13:46
Looks like this actually breaks some uses. In my table with a composite primary key this change produces invalid SQL as well.

In my fork I've reverted the change in the `SQLiteAdapter.php` file and modified the original RegEx instead. You can see it here: https://github.com/lxrco/phinx/commit/1e49983d857de071a580913247d644cfacc58ab1

@pr0ggy - can you try my fork on your specific use-case to see if it still works? If so, I think we should consider using the updated regex instead. It is working for me, and it fixes both the original issue with ENUMs as well as the issue with composite primary keys on tables.

**Comment by lorenzo** [comment] 2017-07-13 14:16
@nebez why not send a pull request with the fix instead?

**Comment by nebez** [comment] 2017-07-13 15:33
Hey @lorenzo - I will definitely send a PR once it's confirmed to be working for more than just my use.

**Comment by lorenzo** [comment] 2017-07-13 15:43
Thanks!

**Comment by pr0ggy** [comment] 2017-07-13 17:18
@lorenzo @nebez tried your regex fix against the unit test updates I created specifically for the enum scenario and they all pass.  I didn't have a particular use case I was testing against, so as far as I'm concerned go ahead and make the PR.  Apologies for the uncaught issue with composite primaries :\

**Comment by nebez** [comment] 2017-07-13 18:10
@pr0ggy - no apology necessary. Your PR helped me narrow down other RegEx issues in the SQLite adapter. And now we have tests thanks to you :) Cheers

**Comment by pr0ggy** [comment] 2017-07-13 18:29
Tests are always good ;) appreciate the work @nebez!

**Comment by tariquesani** [comment] 2017-07-14 03:43
@lorenzo please reopen this issue. There is still some work left to do on this.

**Comment by lorenzo** [comment] 2017-07-14 09:50
@tariquesani what's left?

**Comment by tariquesani** [comment] 2017-07-18 03:38
Now I see the commit :) Everything done
