### ISSUE TITLE
Multiple Databases

### ISSUE THREAD

**Issue by wpillar** [cakephp/phinx#180] opened 2014-02-02 16:08 UTC
It would be cool if Phinx could handle migrations for different databases all from the same instance. In our company setup we have one application which uses n databases, with different migrations for each that need to be handled.

What are you thoughts on handling multiple databases? I might fork and see if I can get it working but I want to know if you'd ever merge something like that?

**Comment by jamespsterling** [comment] 2015-03-18 21:31
+1

**Comment by BardiaAfshin** [comment] 2015-03-19 21:59
The configuration you are proposing doesn't fit being able to drive multiple databases with different revisions. Since sharing the same PhinxLog, you'd be dependent on collapsing the sequencing migrations after another instead hence removing a major flexibility. Unless, that's not a requirement. Then, why not.

**Comment by laurin1** [comment] 2015-03-20 03:35
I know this is kind of a hijack, and apologies....

https://github.com/robmorgan/phinx/issues/515

Actually, having the phinxlog table as part of the same database is a problem for us as well and if we moved instead had a structure like this, maybe it would that part of this issue as well:

* schema: db1
* schema: db2
* schema: phinxlog
** table: db1 (phinxlog table for db1)
** table: db2 (phinxlog table for db2)

**Comment by temperedvision** [comment] 2015-03-24 17:24
Phinx already has the ability to run migrations across different databases without any kind of hack (although the process to set up and use is a little manual/ugly). The solution is simply to use a different config file for each database, and set the migration path to a different sub folder for each DB. Each DB will then have its own migration path and phinxlog table for migration history.

To reduce the amount of code duplication for the configs, I switched my example to use PHP config files. My example also uses $_SERVER vars, as the config in my examples comes from a capistrano integration, but you should get the gist.

file structure:
```
migrations/
| - db1/
| - db2/
| - (etc)
```
db1.php:
```php
$_SERVER['PHINX_DBNAME'] = 'castle';
// set other params here

return include 'phinx.php';
```
phinx.php
```php
return [
	'paths' => [
		'migrations' => 'migrations/' . (isset($_SERVER['PHINX_DBNAME']) ? $_SERVER['PHINX_DBNAME'] : ''),
	],
	'environments' => [
		'default_migration_table' => 'phinxlog',
		'default_database' => 'default',
		'default' => [
			'adapter' => 'mysql',
			'host' => isset($_SERVER['PHINX_DBHOST']) ? $_SERVER['PHINX_DBHOST'] : '',
			'name' => isset($_SERVER['PHINX_DBNAME']) ? $_SERVER['PHINX_DBNAME'] : '',
			'user' => isset($_SERVER['PHINX_DBUSER']) ? $_SERVER['PHINX_DBUSER'] : '',
			'pass' => isset($_SERVER['PHINX_DBPASS']) ? $_SERVER['PHINX_DBPASS'] : '',
			'port' => 3306,
			'charset' => 'utf8',
		],
	],
];
```

This way you can just run your migrations (or other commands) with:
```sh
phinx migrate -c db1.php
```

**Comment by rbalik** [comment] 2015-04-03 20:02
+1

**Comment by kimsyversen** [comment] 2015-04-06 15:11
+1

**Comment by amfriedman** [comment] 2015-04-08 00:06
I think the simplest and most elegant way for phinx to accomplish managing multiple databases is to allow me to couple the migration path with each one of my 'environments' in my config file instead of one global migration path per config file. This would allow me to continue using just one config file to handle multiple databases. For instance (YML style):

    paths:
        # Change this from "migrations" to "default_migrations"
        default_migrations: /path/to/phinx/db1

    environments:

        default_migration_table: phinxlog
        default_database: sandbox

        production:
            adapter: mysql
            host: localhost
            name: db1

        staging:
            adapter: mysql
            host: localhost
            name: db1_staging

         production_other_thing:
            # Add "migrations" path here to override the default
            migrations: /path/to/phinx/db2
            adapter: mysql
            host: localhost
            name: db2
     
        staging_other_thing:
            # Add "migrations" path here to override the default
            migrations: /path/to/phinx/db2
            adapter: mysql
            host: localhost
            name: db2_staging

**Comment by Mechzeit** [comment] 2015-04-10 06:22
+1 @amfriedman
Per-environment configuration of 'migrations' path would be great.

```yaml
environments:
    default_migration_table: phinxlog
    default_database: app1
    app1:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8
        paths: %%PHINX_CONFIG_DIR%%/migrations/app1
    app2:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: ''
        port: 3306
        charset: utf8
        paths: %%PHINX_CONFIG_DIR%%/migrations/app2
```

**Comment by niksamokhvalov** [comment] 2015-06-17 20:44
+1 for this feature!

**Comment by cdburgess** [comment] 2015-06-30 20:09
For multi-tenant databases, we need this feature as well. Interestingly, we cannot manage our various environments outside of their own environment. (i.e. production cannot be accessed outside of the production servers etc.)

To manage the multi-tenancy, I used the environment variable to store all of the databases and their connections. It works like a charm!

- Used a .php file configuration to connect to the system that contains the database connection information and loaded each database config in the environment section of the config

```
return [
	"paths" => [
		"migrations" => "{PATH_TO_MIGRATIONS}"
	],
	"environments" => [
		"default_migration_table" => "{MIGRATION_TABLE_NAME}",
		"{DB1}" => [
			"adapter" => "mysql",
			"host" => $host,
			"name" => {DB1},
			"user" => $username,
			"pass" => $password,
		],
		"{DB2}" => [
			"adapter" => "mysql",
			"host" => $host,
			"name" => {DB2},
			"user" => $username,
			"pass" => $password,
		],
               ...
	],
];
```

- I leave out the `default_database` setting in the config so no database will migrate without specifying it

- Added a snippet of code to the Migrate.php file to recursively loop over the execute to run this on every database in the environment when you run `phinx migrate -e all`

around line 74 of Migrate.php right after  `$environment = $input->getOption('environment');` 

```
if ($environment == 'all') {
            $startAll = microtime(true);
            foreach (array_keys($this->config['environments']) as $environmentName) {
                if ($environmentName == 'default_migration_table') {
                    continue;
                }
                $input->setOption('environment', $environmentName);
                $this->execute($input, $output);
            }
            $endAll = microtime(true);
            $output->writeln('<comment>All databases complete. Took ' . sprintf('%.4fs', $endAll - $startAll) . '</comment>');
            return;
 }
```

- to update any database one at a time, simple pass the name of the database in the environment option in the command line.

```
phinx migrate -e {DB1}
```

If you don't want to have to think about the code, you can get the updated file from my fork here: https://github.com/cdburgess/phinx/blob/0.4.x-dev/src/Phinx/Console/Command/Migrate.php

**Comment by m1ome** [comment] 2015-06-30 23:36
How should be consistency done in this?
When a **DB2** failed transaction and **DB1** already commited it?
What should we do? We will break a db structure/data after migration?

**Comment by cdburgess** [comment] 2015-07-01 14:45
Hey @robmorgan as I look through the code, I am seeing that `environment` is pretty much synonymous with `database`. In fact, the `getEnvironment()` method refers the the `default_database` in the environment section of the configuration. Does this mean that if we want to extend phinx to run migrations on n multi-tenant databases, we should set each database as an environment? Or would you prefer to have a new variable under each environment called `databases` that correspond to a list of databases for that environment?

Right now it's hard to tell which direction one would go to extend the code because environment and database are used somewhat interchangeably. I have a few days of development cycles to dedicate to this issue. I think I can achieve something worth while, but I would love your direction.

**Comment by cdburgess** [comment] 2015-07-01 16:37
@m1ome I have updated the code so it will manage status, rollback, and migration as I described above. In addition, it will try/catch any error on migrate/rollback so the they will continue as normal for the rest of the databases. see: https://github.com/cdburgess/phinx

**Comment by ralphschindler** [comment] 2015-07-01 17:03
Another note to point out: not all commands accept an environment flag.  For example ```create``` does not take environment into account, so you couldn't use that to create a specific migration for a specific database/environment.

**Comment by cdburgess** [comment] 2015-07-01 18:14
Correct! However, that is already inherent in the system. The current way to work around that is to use a different config for the databases that need a different set of migrations. 
`phinx create {MigrationName} -c {config_file}`

However, in a multi-tenancy environment, you are likely to want all of the databases to reflect the same schema as they will likely be running from the same app code. If this is not the case, you will need a separate config file for each one anyway.

**Comment by eko3alpha** [comment] 2015-08-21 12:09
I know I'm one of the people that requested a multiple db feature.  However, after using Phinx for a while, its easy to do migrations on multiple databases without any hacks or updates.
 
Here is my working directory structure:

    /migrations/
                /db1/
                       /migrations/
                       /phinx.yml
                /db2/
                       /migrations/
                       /phinx.yml
                /db3/
                       /migrations/
                       /phinx.yml


Open terminal in each one of the db directories and execute the migration.

    eko3alpha:/migrations/db1/$ phinx migrate -e testing

I've grown to love this approach for its clear separation.  Don't forget to install Phinx globally and run the migrate command inside the respective directory.

Thanks @robmorgan for your awesome work!

**Comment by robmorgan** [comment] 2015-08-22 15:20
@eko3alpha thx for your suggestion. Indeed its probably the best work around for now. I'll refer people to this until we consider something more integrated.

**Comment by niksamokhvalov** [comment] 2015-09-13 12:15
I use Phinx migrations for multiple databases. My structure directory:

```
migrations/
     .db1/
     .db2/
     .db3/
     db1.yml
     db2.yml
     db3.yml
```

Console commands for migrate one DB:
```
php phinx:migrate -c migrations/db1.yml
```
Migrate all DB:
```
php phinx:migrate all
```

Console command for executing migrations of the all shards: https://gist.github.com/niksamokhvalov/3dace9bee42bc76c5f8a

**Comment by daverogers** [comment] 2015-12-19 01:41
@eko3alpha - great solution. That worked for me :+1:

**Comment by mnpenner** [comment] 2016-01-25 18:17
I need this feature too, but I think my setup is different than everyone else's. 

I want to run *the same* migrations across *many* databases (~400), except in some circumstances where a few DBs should be excluded.

The way I see this working is that each migration file should have a `shouldRun($databases)` method wherein you can filter through the list of databases before the migration is run. PhpMig would need to keep track of which databases it has been ran on/which ones it's skipped.

I would want this migration data stored in its own DB so that it doesn't have to connect to 400 different DBs to figure it out.

**Comment by JCMais** [comment] 2016-02-16 15:59
Have same setup than @mnpenner, I'm currently building a SaaS application, and each client has their own database, the databases have the same structure, so there is only one migration that should run in all databases.

**Comment by janvandijk** [comment] 2016-03-18 09:39
@mnpenner & @JCMais Same setup here. One master database and 100s+ tenant databases (on the same mysql instance).

We need to be able to both migrate the master database as the tenant databases.

Any progress in making this work? And/or nice hacks / workarounds people have found?

**Comment by mnpenner** [comment] 2016-03-18 18:09
@janvandijk I started my own library. I'm not sure I'll be able to open-source it though; it's kinda specific to our platform.

**Comment by JCMais** [comment] 2016-04-11 18:18
@robmorgan Any plans for that feature? I see that you got the milestone assigned to it, do you already know how you plan to implement it? If yes, can you share.

**Comment by ahmadarif** [comment] 2016-06-01 23:21
+1 for this feature :+1:

**Comment by Henk8** [comment] 2016-06-30 13:10
Same setup here. +1 for this feature

**Comment by wzrigui** [comment] 2016-07-28 08:57
+1

**Comment by nitesh-fiestel** [comment] 2016-08-10 07:00
+1

**Comment by thorne51** [comment] 2016-08-25 13:57
+1

Our application uses one master database which is copied for every client added to the system. So when we do a migration on the master database, we would need to apply the same changes to the client system.

Maybe we could possibly specify database/schema as an option to the $this->table() function?

**Comment by JCMais** [comment] 2016-08-25 14:25
the best option in my opinion is to pass the databases directly to the migrate command.

**Comment by thorne51** [comment] 2016-08-27 20:50
@JCMais I'd need to be able to execute that migrate command from my migration in that case. Would you be able to help out with a code example of how to accomplish this please?

The list of client databases is around 50 and is programmatically created, and retrieved. So what I'd like to do is be able to execute the current migration on an array of database names. Originally I thought of just having the phinxlog table on the main master database and just executing the queries on each of the client databases. But if I can programmatically run the actual migration on the client database with its own phinxlog table that would be fine as well.

Thanks!

**Comment by JCMais** [comment] 2016-10-08 21:38
@thorne51 your use case is identical to mine, I misread your initial comment.

**Comment by thorne51** [comment] 2016-10-10 06:52
@JCMais I ended up just using our own database class and executing the queries manually, and essentially using phinx as a wrapper for migrations, with the migrations only being recorded in the main database.

offtopic: Thanks! Got it from the fan site kit a while ago! Yours is great too! Some [info](http://n4g.com/news/1391946/what-vault-boy-is-really-doing-with-his-thumb) on yours ;)

**Comment by JCMais** [comment] 2016-10-10 17:04
@thorne51 how are you handling failed migrations?

**Comment by webdevbyjoss** [comment] 2016-11-30 22:02
+1

**Comment by atippett** [comment] 2016-12-10 22:47
I'm seeing a lot of talk about multiple databases with a sprinkle of multiple schemas.  My situation is we have the same schema for each of our customers that we have to push updates to.  There might be 100+ schemas but we want to keep them all the same.  Has anyone figure how to accomplish this with phinx without having to specify configuration for each schema?

**Comment by thorne51** [comment] 2016-12-15 06:24
@atippett Currently I just create SQL scripts and use our own system's database adapter class to run the scripts on multiple databases. In this scenario, I only use phinx to track (on my main database) which migrations have been run and which haven't.

**Comment by daniel-gomes-sociomantic** [comment] 2017-04-19 13:56
+1

**Comment by duraki** [comment] 2017-07-12 07:22
2014 - 2017, so many requests for the feature and not a single proper solution or pull request. Great. Just great.

**Comment by duraki** [comment] 2017-07-12 07:31
Any update to not using workaround? Pull request? Anything? Jesus, 4 year passed and this issue is still open. Great. Just great.

**Comment by lorenzo** [comment] 2017-07-12 14:24
@duraki Maybe the lack of interest in sending a pull request for this feature shows that it is actually not necessary to have it in this repo.

One simple way of having multiple configurations per environment is to have a script swapping the files and then run the executable. 

That option also makes phinx a lot more secure, as you won't be committing these files with credentials into git by mistake.

**Comment by duraki** [comment] 2017-07-12 15:36
@lorenzo Thank you for the input. I agree this feature did not attract many, maybe since some  architectures (eg. microservice) is yet to arise in a PHP-based environments. You can actually see the comments being more regular lately on the issue with the applied tenancy on different projects.

On other hand, I've seen cases of uninterested, since no pull was proposed, or no proper solution was commented for a long time, therefore no change would be made even if commenting/requesting the feature.  
  
Anyway, I hope to see this sometimes bundled with phinx.

Regards.

**Comment by friebe** [comment] 2017-09-14 13:29
Nice to see your post.  Can u post your folder structure pls ?

**Comment by rohithb** [comment] 2017-09-14 13:45
@friebe Sure.
```
project/
├── db/
│   ├── migrations/
│   ├── seeds/
│   └── migrationRunner.php
├── src/
├── vendor/
├── composer.json
└── phinx.yml

```
the exact command is `php db/migrationRunner.php` running from project root.
**phinx.yml**
```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds

environments:
    default_migration_table: phinxlog
    default_database: development
    development:
        adapter: mysql
        host: localhost
        name: %%PHINX_DBNAME%%
        user: root
        pass: 'PASSWORD'
        port: 3306
        charset: utf8

version_order: creation
```
You need to put  `%%PHINX_DBNAME%%` as `name` in environment for loading it from `$_SERVER` variable.

**Comment by friebe** [comment] 2017-09-14 14:33
@rohithb thx. it helps a lot. I noticed that the autoloader which load the `\Phinx\Console\PhinxApplication()` object is missing. 

I tryed to put `$autoloader = require __DIR__ . '/../robmorgan/phinx/src/composer_autoloader.php';` at the beginning of the  migrationRunner. But it dont helps me. Maybe any idea ?

**Comment by rohithb** [comment] 2017-09-14 15:39
@friebe  I edited the actual post and added the line which imports `autoload.php`.  Please check it.
In order to use composer dependencies, you should include `vendor/autoload.php` in your project.
You are importing the wrong file.

**Comment by friebe** [comment] 2017-09-14 16:39
@rohithb It works find. Save my da.

**Comment by johnrobertporter** [comment] 2017-09-22 19:29
If we all look at this from the config outwards for now, to tackle multiple databases inside multiple environments:

```yaml
paths:
  migrations: /migrations
  seeds: /seeds

environments:
  default_migration_table: _migrations
  default_database: development
  production:
  - adapter: mysql
    host: localhost
    name: production_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  testing:
  - adapter: mysql
    host: localhost
    name: testing_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  development:
  - adapter: mysql
    host: localhost
    name: development_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  version_order: creation
```

This would provide an 'environment' array of database instances.

If this is coupled with the multiple folder setups as described in use cases above:

```
/databases
    /tenant
        /migrations
        /seeds
        /phinx.yml
    /system
        /migrations
        /seeds
        /phinx.yml
```

This would allow multiple 'collections' of environments and databases.

---

So, code wise, we put the folder structure to one side. This gives us the following rules to work towards:

- [x] Must be able to migrate multiple environments. (done in phinx already!)
- [ ] Must be able to migrate multiple databases within each environment

Once that is solved, basically the problem is solved. If after that, a wrapper wants to be made to sit outside a folder structure, that can't be too complicated.

I'm starting to look into this, so if anyone knows any caveats I might encounter, please let me know!

**Comment by broberts-mrmc** [comment] 2017-09-22 23:35
+1

In the YAML configuration file example, did you intent to provide a multi-environment and database example?

On Sep 22, 2017, at 2:29 PM, John Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


If we all look at this from the config outwards for now, to tackle multiple databases inside multiple environments:

paths:
  migrations: /migrations
  seeds: /seeds

environments:
  default_migration_table: _migrations
  default_database: development
  production:
  - adapter: mysql
    host: localhost
    name: production_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  testing:
  - adapter: mysql
    host: localhost
    name: testing_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  development:
  - adapter: mysql
    host: localhost
    name: development_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  version_order: creation

This would provide an 'environment' array of database instances.

If this is coupled with the multiple folder setups as described in use cases above:

/databases
    /tenant
        /migrations
        /seeds
        /phinx.yml
    /system
        /migrations
        /seeds
        /phinx.yml


This would allow multiple 'collections' of environments and databases.

________________________________

So, code wise, we put the folder structure to one side. This gives us the following rules to work towards:

  *    Must be able to migrate multiple environments. (done in phinx already!)
  *    Must be able to migrate multiple databases within each environment

Once that is solved, basically the problem is solved. If after that, a wrapper wants to be made to sit outside a folder structure, that can't be too complicated.

I'm starting to look into this, so if anyone knows any caveats I might encounter, please let me know!

**Comment by johnrobertporter** [comment] 2017-09-23 10:39
That is the multi environment multi database example, not the dash before the adapter key, this makes anything below it a complete item, so if you were to add another one, it would be separate.

```yaml
paths:
  migrations: /migrations
  seeds: /seeds

environments:
  default_migration_table: _migrations
  default_database: development
  production:
  - adapter: mysql
    host: localhost
    name: production_db
    user: root
    pass: ''
    port: 3306
    charset: utf8
  - adapter: mysql
    host: localhost
    name: production_db_2
    user: root
    pass: ''
    port: 3306
    charset: utf8

  testing:
  - adapter: mysql
    host: localhost
    name: testing_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  development:
  - adapter: mysql
    host: localhost
    name: development_db
    user: root
    pass: ''
    port: 3306
    charset: utf8

  version_order: creation
```

Above is a better example.

**Comment by johnrobertporter** [comment] 2017-09-23 17:03
This is in fact a lot more complicated than I first imagined.

My intent was to move the functionality of `Environment` into a new class `Database` and then run loops inside `Environment` or `Manager` to get the correct data. I've already hit the wall

>What happens if a migration fails on one database and not another?

I suppose it would be logged in that database, but how would one re-run a single database? I haven't got sufficient an answer for questions like that, so I may have to hold off on this and use Phinx alongside Deployer to get the functionality I need quickly.

**Comment by broberts-mrmc** [comment] 2017-09-23 20:08
Some thoughts...

1. Seems commands with support for "-e" (environment) option would need support for a new option, maybe  "-n" ([database] name) since "-d" is already used for "date". The new option could be used to specify the specific database [name] within an environment if, for example, with the MIGRATE command, all databases in an environment (default or otherwise) should not to be migrated.

2. I'd assumed the use case for multiple databases was "multiple dissimilar databases" used by a single project (e.g. ERP database, HR database) rather than "multiple similar or identical databases" (e.g. HR database #1, HR database #2). In the the former case, it seems it would be less problematic if a migration failed on one database and not the other as the migrations would likely also be dissimilar. You may have a different use case in mind.

Ben Roberts
903-520-4774
On Sep 23, 2017, at 12:03 PM, John Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


This is in fact a lot more complicated than I first imagined.

My intent was to move the functionality of Environment into a new class Database and then run loops inside Environment or Manager to get the correct data. I've already hit the wall

What happens if a migration fails on one database and not another?

I suppose it would be logged in that database, but how would one re-run a single database? I haven't got sufficient an answer for questions like that, so I may have to hold off on this and use Phinx alongside Deployer to get the functionality I need quickly.

**Comment by broberts-mrmc** [comment] 2017-09-23 20:26
Also, if you're already bootstrapping your own database configuration using the PHP format phinx configuration, I think a recent pull/merge makes multiple databases possible, though not quite in the same way: #1070

On Sep 23, 2017, at 12:03 PM, John Porter <notifications@github.com<mailto:notifications@github.com>> wrote:


This is in fact a lot more complicated than I first imagined.

My intent was to move the functionality of Environment into a new class Database and then run loops inside Environment or Manager to get the correct data. I've already hit the wall

What happens if a migration fails on one database and not another?

I suppose it would be logged in that database, but how would one re-run a single database? I haven't got sufficient an answer for questions like that, so I may have to hold off on this and use Phinx alongside Deployer to get the functionality I need quickly.

**Comment by mvrhov** [comment] 2017-09-25 08:31
Just do multiple environments and prefix each environment with the database name. IMO having multiple databases in one app is not that common.

**Comment by johnrobertporter** [comment] 2017-09-25 11:18
It is in a multi-tenant application; we have one system database, and `n` client databases which would need migrating. We would duplicate one or more of these into say `development` environment, so would need to handle multiple environments with multiple databases inside these.

I wouldn't want to migrate 100+ environments ;P

**Comment by duraki** [comment] 2017-09-25 11:55
For some reason, `phinx` contributors really try hard to avoid this feature request. I mean, multi-tenancy app isn't something new these days. Therefore, we can all agree that this issue became a hot topic since the last update from @lorenzo (ignored it, since the lack of priority and PR).
  
I'd gladly send a pull request, the problem is, we can't describe a proper design pattern for this case. Can we switch current topic from an actual "issue" (for which we got notice from year ago), and move towards to engineering discussion so we can finally see this in master.
  
A few of really interesting solution approaches are in comments for this issue, yet we all "hack" the way around it.

**Comment by broberts-mrmc** [comment] 2017-09-25 13:12
I think the problem (or need) is simple and clearly defined, but seems there's more than one use case mentioned throughout the comments in this issue. What follows is an attempt to define the use cases (in no particular order):

1. Multi-Tenancy DBMS (i.e. one common database and/or multiple similar/identical databases in one project and for each environment) -- I see this as a reasonable/valid use case, though the original description provided by @wpillar in 2014 doesn't seem to contemplate this.

2. Multiple, Dissimilar Databases (i.e. different databases in one project and for each environment) -- I see this as another reasonable/valid use case.  It's the one I have in mind (e.g. one project with an ERP database and HR database; multiple environments too, of course).

These two use cases seem to have some divergent needs.  For example, it seems "migrations failures" require more delicate treatment in one case (# 1) and not the other.  I think a good starting point would be to clearly define the use case(s) that would/should be addressed in an engineering discussion, design, etc. There may be other uses cases not readily apparent to me. Thoughts?

**Comment by dig412** [comment] 2018-01-30 15:09
Thanks @broberts-mrmc, excellent summary. I made a couple of diagrams of these use cases, mostly for my own benefit to help visualise the problem.

## Multiple, Dissimilar Databases
As always naming is an issue. Phinx gives us "environment" which works well, but what is the other grouping called? It's called database in this issue, but that's an overloaded term, especially as the Phinx config calls the default environment `default_database`.

I call this grouping database, with each instance of a database in an environment (app in dev, app in prod, etc) called a schema. As this wording isn't used elsewhere in Phinx I'm not sure how useful this is.

![phinx-multi-service](https://user-images.githubusercontent.com/1693435/35572540-ba692532-05cc-11e8-80f6-2fa78c4e66c4.png)

Each coloured band has a separate table structure, separate migrations, and a separate migration log table.

This is the use case that's handled fairly well by having multiple distinct Phinx directories with a config file for each as @eko3alpha suggested a while back. 

It probably wouldn't be too difficult to internalise this structure within Phinx, with per-environment and per-database config values for migration directory and migration table, as in this fantasy example:

```
environments:
  default_migration_table: phinx_migrations
  default_environment: development
  development:
    application_db:
      host: localhost
      schema: application_db
      migration_table: phinx_migrations_application
    user_db:
      host: localhost
      schema: user_db
      migration_table: phinx_migrations_user
  production:
    application_db:
      host: prod.server
      schema: application_db
      migration_table: phinx_migrations_application
    user_db:
      host: prod_user.server
      schema: user_db
      migration_table: phinx_migrations_user
```
Issues with this - it's quite verbose, as the config is effectively 2D we end up duplicating per-database values for each environment, or per-environment values per DB if we were to flip the structure. Any suggestions?

## Multi Tenancy
I'm less clear about what to do with this, as it's not the way our app works or the way I use Phinx. 

![phinx-multi-schema](https://user-images.githubusercontent.com/1693435/35573337-bb0eded0-05ce-11e8-984c-e8c34a204be2.png)

@johnrobertporter has suggested a config format that makes sense to me - an array of multiple schema connection details to be used. As many have pointed out the issue with this use-case is commit/rollback behaviour across multiple schemas/servers. This looks like the hardest decision to make to resolve this issue.

Should Phinx proceed across all schemas regardless of failure, or should it roll back all in case of a single failure? Perhaps this could be configurable behaviour?

**Comment by fengxw** [comment] 2018-04-25 12:15
sad about this issue still is opened! i think it's a common issue for a project composed of many modules. whatever, maybe @eko3alpha 's solution is best for now,  and we can make a command to run all the migrations which in different db automatically.  anyway, hope to have an official solution.

**Comment by JayPHP** [comment] 2018-04-25 12:56
@fengxw If you have a fix in mind, please don't hesitate to submit a PR :)

**Comment by JayPHP** [comment] 2018-04-25 12:58
@lorenzo @dereuromark Any thought on an approach for this?

**Comment by JapSeyz** [comment] 2018-04-30 06:14
@lorenzo What do you mean? I think you tagged me by mistake instead of JayPHP?

**Comment by lorenzo** [comment] 2018-04-30 08:47
@JapSeyz sorry, I did mean to tag him.

**Comment by johnrobertporter** [comment] 2018-05-21 12:30
@lorenzo I think that's not the right solution. Environments and databases has been confounded due to the fact that Phinx is a single database application; environments is the correct term to use as it talks about local vs production for example. We need to have databases added as a term, and the merging of terms in the codebase needs to be split out properly.

**Comment by njake** [comment] 2018-05-22 08:48
@johnrobertporter Agree, environment is not way, environment != databases
We have over 1000 databases dynamically created, environments is not way at all.

**Comment by johnrobertporter** [comment] 2018-05-22 17:20
>Would renaming environments to database help?

This is what I'm trying to say i the wrong approach.

> What's being discussed here is the ability to use different configurations, we already have that feature.

The general topic of this thread is about having multiple databases within the environments we use like `local`, `testing`, `production` et al.

I understand that using multiple configuration files is a solution, but for me it's a temporary one at best. @broberts-mrmc and @dig412 have summed it up the best so far.

There needs to be a new concept inside the codebase `Database` alongside `Environment`. That will pave the way to the separation of concerns and slowly allow the ability to add multiple databases.

I really wish I had time to offer to really look into this as I would love to give it a go.

**Comment by lorenzo** [comment] 2018-05-22 17:31
maybe those who really understand the need for this and why having multiple configuration files is not a solution can contribute the code for it?

I really cannot see how multiple files or templting a single config file using an external script fails to solve this problem.

**Comment by rohithb** [comment] 2018-08-14 17:52
Hi, We have been using a wrapper for Phinx to migrate hundreds of databases for our application little over a year.  
Check [https://github.com/linways/phinx-multiple-database](https://github.com/linways/phinx-multiple-database) .

This is not a neat solution, its just a hack. But I hope this will be helpful.

**Comment by jszoja** [comment] 2018-08-26 01:46
I started working on a very simple concept in [jszoja/phinx](https://github.com/jszoja/phinx/wiki) in multidb branch if anybody is interested. So far it worked for both migrations and rollbacks. Testing on mysql only.
It assumes that the all databases resides on the same server, but I believe it can be easily modified to suit distributed databases through multiple servers.

**Comment by piotr-cz** [comment] 2018-11-22 12:06
Guys, look at #1241

**Comment by lorenzo** [comment] 2018-11-22 15:01
Unfortunately that branch is not up to date and did not pass the tests @piotr-cz

**Comment by keithy** [comment] 2019-06-05 19:33
I have looked at these issues, and incuded some solutions in my own PDO library available here:

https://github.com/keithy/primo-pdo-php

The solution I have come up with starts by enabling my code to access Phinx as normal code, not as a wrapped up command line tool. This allows the primo-pdo library to prepare a bespoke $config array, and invoke phinx with it directly, supplying a custom PDO instance.

[I think that this approach should be documented and Phinx refactored so that this interface to Phinx is a typical use case (removing as many dependencies i.e. Console I/O) from the core code.] 

Features:

The custom PDO instance has per-adapter helpers, which can iron out some of the differences between database sql implementations. e.g CONCAT vs ||.

The config file can then be adapted to provide lots of cool features, such as:

* merging in settings from a defaults file
* merging per-adapter settings into environments

This then enables other features to be applied on a per-adapter or per-environment basis:
* including a specified migration state per adapter/environment (for fixtures)
* the option of per-environment/per-adapter paths
* and optional overrides, e.g. 'backup', 'snapshot' (i.e. use the environment with a different database host) for backups.
* and last minute %%PER_CLIENT%% variable substitution.

Example Use:
```
$test_fixture = $reader
     ->choose('empty')
     ->which('snapshots')
     ->recreate()
     ->copyTo( $reader->choose('empty') );
```
Selecting the "empty" environment, apply the optional configuration "snapshots", which changes the working directory to a cache of pre-prepared fixtures. In that folder, delete any existing database, and create a new one by applying migrations, and seeders as specified within the "empty" environment. Copy the result to overwrite the normal "empty" database, returning the result as the fixture... Oh and then we want to use the database in a test case!
```
$query = ""
$pdo = $test_fixture->pdo()->addLog( function( $sql ) use($query) { $query = $sql } );
// perpared stmt
assert( $pdo->run("SELECT count(*) WHERE name IS ?", "Rob")->fetchColumn == 1 );
assert( $query == "SELECT count(*) WHERE name IS `Rob`" );
```

This is pretty handy, and requires no changes to Phinx. I think that this approach would free Phinx from more complex and use-case specific feature requests.

Phinx could be improved by either adopting some of these ideas, by simplifing or both.

I would suggest a little refactoring, so that internally "MigratorCore" only accepts a single environment with all of the parameters that it needs, called by "PhinxCore", which processes the existing Phinx file formats as it does currently. Then my library and others like it can use MigratorCore, knowing that the interface will remain stable. PhinxCore can then include improvements that are backwards compatible, or Phinx2Core can break the mold.

If the command line tool is improved to accept a parameter, that selects the Core implementation class, it can be used with a range of configuration files, with "MigratorCore"  (single environment array and no frills), "PhinxCore" (default backwards compatible), "Phinx2Core" (including new ideas), or "MyOwnConfigTweakingClass". The result being, that now I would have a commandline tool, which fully supports all the features of the pdo library I am using.

**Comment by keithy** [comment] 2019-06-06 03:18
I have implemented the initial refactoring to which I referred above and have attempted to run the tests. If you are interested the code is available for review at http://github.com/keithy/phinx

**Comment by dereuromark** [comment] 2020-04-11 06:08
PR welcome.

**Closed by dereuromark** 2020-04-11 06:08 UTC
Labels: feature, waiting on feedback

**Comment by ihommani** [comment] 2020-05-07 08:07
Hi @dereuromark , I didn't get the status of the feature. This thread is closed and points to an enhancement that is closed but unmerged.  Is this feature put aside for the moment?
thx

**Comment by ihommani** [comment] 2020-05-07 08:35
My personnal opinion on the feature is although it answers direct needs of many users (including myself) I can't stop to think that we may open a pandora's box by including it in the phinx core. 
Phinx is designed to be mono DB. More precisely, a Phinx execution/run is monoDB. 
That allows the tool to be driven by KISS principles that I really appreciate. Previous comments proposed several quickwins that I find acceptable. As far as I am concerned, I define a phinx.yml per Database (each one in a folder named after de database) and orchestrate the overall seeding/migration through a simple script.

**Comment by keithy** [comment] 2020-05-07 18:53
My suggestion would be, to look a bit more closely at the utility that you can get if you implement a few simple suggestions above, particularly accepting a connection array instead of the connection string.

I found the end result satisfying, particularly the ability to use phinx for generating fixtures to test against. (Unfortunately I will not be working with PHP for a good while)

The full refactoring suggested was not difficult but neither was it trival to finish in the time I had available.
