### ISSUE TITLE
Create an Initial Migration from an Existing Database

### ISSUE THREAD

**Issue by ylynfatt** [cakephp/phinx#109] opened 2013-07-11 20:23 UTC
Is it possible for Phinx to create an initial migration from an existing database? My scenario is that I have an application with a database and it's tables already and I'd like to start using Phinx to handle my migrations (previously i was manually creating SQL scripts). I'd love if Phinx could inspect my database and create an initial migration file with the current table structures as a starting point.

I hope that made sense.

**Comment by shadowhand** [comment] 2015-01-07 18:08
@dimz119 @detook #249 added support for `longtext` and `tinytext`, among others.

**Comment by shruthi-ananth** [comment] 2015-01-21 17:21
Thank you @detook. It worked great for me too. But I had to switch over to the dev-master due to newer type support added in the later branches. Can we merge this with current dev-master? It's a great feature to have.

**Comment by detook** [comment] 2015-01-21 17:44
Yes, I'm planning to maintain fork in future. I just not sure that I'll have time this January.

**Comment by shadowhand** [comment] 2015-02-02 02:47
@detook:
>  I'm planning to maintain fork in future

Why would you try to maintain a fork, rather than sending a PR?

**Comment by detook** [comment] 2015-02-02 08:46
@shadowhand it's already here #192

**Comment by rbalik** [comment] 2015-03-13 21:38
Looks like that pull request is closed. Still any plans to merge this in? It would be great to have.

**Comment by shadowhand** [comment] 2015-03-15 15:05
@rbalik the pull request was closed because it was made against an outdated branch. Hopefully @detook chooses to recreate it.

**Comment by detook** [comment] 2015-03-15 18:31
I don't have time to review changes between 0.3.x and 0.4.x to create good PR at this moment. But I definitely won't leave it. I'll try to find time on weekends in March.

**Comment by davila7** [comment] 2015-04-06 13:16
When I run this command "shema: dump" I lose all data. There is a command for the shema and also the data in the tables?

**Comment by detook** [comment] 2015-04-07 09:12
@davila7 both dump and load designed to work only with schema.

**Comment by davila7** [comment] 2015-04-07 13:30
@detook Ok, but There is a type of command that handles the data?

**Comment by lorenzo** [comment] 2015-04-07 14:02
@davila7 `mysqldump`

**Comment by davila7** [comment] 2015-04-07 14:22
mysqldump is to backup, I need something like that:

//schema
public function change(){
$user = $this->table('user');
$user->addColumn('name', 'string', array('limit'=> 40))
         ->save();

$this->execute("INSERT INTO 'user' ('name') VALUES
('davila7');");
}

or just the insert, since the structure gives me schema:dump

**Comment by sabl0r** [comment] 2015-04-10 19:20
Awesome feature!
@detook Are you planing to include the current migration version into your dump? Like [ActiveRecord](http://edgeguides.rubyonrails.org/active_record_migrations.html#what-are-schema-files-for-questionmark) is doing it? This would allow us to skip migrations, which are already covered by the latest dump after doing a `schema:load` on a fresh database.
I tried the schema-dump branch of your repo and this is missing at the moment.

**Comment by liaogz82** [comment] 2015-04-22 08:17
+1

**Comment by gwagroves** [comment] 2015-05-07 10:08
I've created a simple standalone php cli script to generate phinx migration commands for an existing MySQL database, if any one is interested: https://github.com/gwa/MySQL2Phinx

(Not all features are currently implemented, but it's better than creating all the commands manually.)

**Comment by gmansilla** [comment] 2015-09-08 13:38
Another way of accomplishing this is:

Generate a sql dump with everything (structure + data) 
Create an initial migration file and have phinx to execute that sql file

Although I am not sure if this is correct approach.

**Comment by DanHulton** [comment] 2015-09-08 19:20
That's how we do it right now, but it's not great.  If you want to then push your migrations into production, you have to init phinx to make sure the migrations table exists, then manually make entries to skip over your sql dump migration, THEN run the rest of your migration scripts.  This can be error-prone, and the error in question (accidentally corrupt your live data) is pretty horrific.

**Comment by beporter** [comment] 2015-10-07 14:22
See also #350, which would seemingly solve this problem as a subset of the larger problem of _generating_ migrations from a live DB.

**Comment by mathieuimbert** [comment] 2016-03-11 15:55
Is anyone still interested in this feature? I'm working on a 'phinx revert' command that would allow one to create a migration based on an existing database.

**Comment by rbalik** [comment] 2016-03-14 03:23
I ended up doing it manually, so don't need it right away, but definitely seems useful.
(And yeah, doing it manually was a huge pain.)

**Comment by albertleao** [comment] 2016-05-18 06:03
+1

**Comment by J-Fricke** [comment] 2016-05-20 22:32
+1
This would definitely be a useful addition to this tool. I'm going to have to take a look at the implementation @gwagroves listed until this is part of Phinx.

**Comment by janreges** [comment] 2016-05-23 09:32
+1

**Comment by BassemN** [comment] 2016-05-23 14:31
:+1:

**Comment by ludalex** [comment] 2016-06-07 11:14
👍

**Comment by angular-tools** [comment] 2016-06-12 00:00
This is definitely a much wanted feature. I see two or three people have attempted this, so I hope something works out :+1:

**Comment by basilfx** [comment] 2016-06-16 14:39
I picked up where @warnero [left off](https://github.com/warnero/phinx).

* Rebased onto latest development version
* Bugfixes
* Parsing MySQL enum's
* Working on SQLite interface

So far I can dump a MySQL database and load it into SQLite or MySQL. However, foreign keys are not (yet) supported, which is something I can live with for now.

Check if out at https://github.com/basilfx/phinx/tree/feature/schema.

**Comment by jimsandwick** [comment] 2016-06-21 17:32
@basilfx Hi. I'm really interested in the 'Create an Initial Migration from an Existing Database'. Is this possible with the changes you have made? I am unable to see the functionality in the documentation, commands. 

How are you dumping and loading into MySQL through Phinx?

Regards,

**Comment by basilfx** [comment] 2016-06-21 18:06
@jimsandwick You can use `phinx schema:dump` to create an initial database schema of the tables in your database, and `phinx schema:load` to load that schema into your database. This will destroy your existing database, so be careful.

The commands aren't documented (yet).

**Comment by jimsandwick** [comment] 2016-06-21 18:09
@basilfx Thanks very much. I should of read more of the comments above. Thanks for your time and effort. Regards,

**Comment by basilfx** [comment] 2016-06-22 15:12
@jimsandwick I have updated the repository:

* `0.5.x-dev`: https://github.com/basilfx/phinx/tree/0.5.x-dev
* `0.6.x-dev`: https://github.com/basilfx/phinx/tree/0.6.x-dev (latest)

From `0.5.x-dev` to `0.6.x-dev` was a bit more painful, but it seems to work. I also added some documentation.

**Comment by jimsandwick** [comment] 2016-06-22 15:15
@basilfx Thanks very much. Will be having a play around soon. Thanks again.

**Comment by adduc** [comment] 2016-08-23 20:04
@basilfx Looks like a great start. Any plans to add support for indexes when dumping the schema?

**Comment by celorodovalho** [comment] 2016-09-01 17:06
+1 :+1:

**Comment by basilfx** [comment] 2016-09-02 07:03
@adduc Sorry, don't have the time to do active development. I only do bug fixes for the project I use it for. Feel free to add it :-)

**Comment by basilfx** [comment] 2016-09-26 10:25
I have updated the repository:

* 0.5.x-dev: https://github.com/basilfx/phinx/tree/0.5.x-dev
* 0.6.x-dev: https://github.com/basilfx/phinx/tree/0.6.x-dev
* 0.7.x-dev: https://github.com/basilfx/phinx/tree/0.7.x-dev (latest)

Initial support for dumping foreign keys is included in `0.7.x-dev` (MySQL only).

**Comment by andrezap** [comment] 2016-10-07 17:31
Can anyone tell me how can I use the version that @basilfx has created?

**Comment by celorodovalho** [comment] 2016-10-07 19:20
@basilfx can you merge my pull request to yours?
https://github.com/robmorgan/phinx/pull/955

**Comment by basilfx** [comment] 2016-10-10 05:41
@andrezap Easiest is to add this to your `composer.json` file:

```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/basilfx/phinx"
        }
    ],
    "require": {
        "robmorgan/phinx": "dev-0.7.x-dev",
    }
}
```

@celorodovalho I can, but please rebase onto 0.7.x-dev and create a PR [here](https://github.com/basilfx/phinx/pulls).

**Comment by bensinclair** [comment] 2016-10-21 05:37
@andrezap Once you do what @basilfx suggested you then run the following in command line:

`vendor/bin/phinx schema:dump`

**Comment by andrezap** [comment] 2016-10-24 17:53
@bensinclair  @basilfx  Thank you!

**Comment by MACscr** [comment] 2016-10-28 08:04
Odd that it still shows me as using 0.6.4
```
webusr@id-4:/var/www/html$ cat composer.json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/basilfx/phinx"
        }
    ],
    "require": {
        "mobiledetect/mobiledetectlib": "^2.8",
        "namshi/ab": "^1.1",
        "kassner/log-parser": "^1.1",
        "robmorgan/phinx": "dev-0.7.x-dev"
    }
}
webusr@id-4:/var/www/html$
webusr@id-4:/var/www/html$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing robmorgan/phinx (v0.6.5)
  - Installing robmorgan/phinx (dev-0.7.x-dev 2edf860)
    Cloning 2edf86092de87c0478126cfe02c7c406fba8aa96

Writing lock file
Generating autoload files
webusr@id-4:/var/www/html$ vendor/bin/phinx schema:dump
Phinx by Rob Morgan - https://phinx.org. version 0.6.4

using config file ./phinx.yml
using config parser yaml
using migration paths
 - /var/www/html/sql/migrations
using seed paths
PHP Fatal error:  Uncaught Error: Class 'Phinx\Console\Command\ConfirmationQuestion' not found in /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/SchemaDump.php:45
Stack trace:
#0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/SchemaDump.php(120): Phinx\Console\Command\SchemaDump->getCreateMigrationDirectoryQuestion()
#1 /var/www/html/vendor/symfony/console/Command/Command.php(256): Phinx\Console\Command\SchemaDump->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Application.php(820): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\SchemaDump), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput in /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/SchemaDump.php on line 45
```

**Comment by basilfx** [comment] 2016-10-28 08:22
Try to remove the `/var/www/html/vendor/robmorgan/phinx/` folder, the run `composer install`. Version `2edf86092de87c0478126cfe02c7c406fba8aa96` is the right one.

**Comment by MACscr** [comment] 2016-10-28 08:28
Tried the following (replacing the bin as well with no diff), but still get the same exact error as I reported earlier:

```
webusr@id-4:/var/www/html$ rm -rf /var/www/html/vendor/robmorgan/phinx/
webusr@id-4:/var/www/html$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing robmorgan/phinx (dev-0.7.x-dev 2edf860)
    Cloning 2edf86092de87c0478126cfe02c7c406fba8aa96

    Skipped installation of bin bin/phinx for package robmorgan/phinx: name conflicts with an existing file
Generating autoload files
webusr@id-4:/var/www/html$
```

**Comment by MACscr** [comment] 2016-10-30 03:53
No other ideas? Am I somehow missing a dependency that hasn't been listed? I've only installed the required symfony packages, I'm not using symfony in general. Though i dont think thats the problem since the version that is being listed when i run the command is the 0.6.x version and not the 0.7.x version, so obviously need to solve that first.

**Comment by casimcdaniels** [comment] 2016-11-04 18:36
I'm trying what @basilfx suggested, and it doesn't appear to do anything besides load the config and paths.

$ vendor/bin/phinx schema:dump
Phinx by Rob Morgan - https://phinx.org. version 0.6.4

using config file .\phinx.yml
using config parser yaml
using migration paths
 - C:\Users\Casi\Projects\dots-dev\db\migrations
using seed paths

**Comment by futoase** [comment] 2016-11-07 17:24
@mackstar 

This may be the cause
https://github.com/basilfx/phinx/pull/1/files#diff-61a9b7867c140a3e0008beba372d8cd4R10

**Comment by basilfx** [comment] 2016-11-12 12:59
I have updated the [`0.6.x-dev`](https://github.com/basilfx/phinx/tree/0.6.x-dev) fork and the [`0.7.x-dev`](https://github.com/basilfx/phinx/tree/0.7.x-dev) fork.

The `0.7.x-dev` fork contains support for [dumping indexes](https://github.com/basilfx/phinx/pull/1) (contributed by @jwh315, MySQL-only).

**Comment by HanXHX** [comment] 2016-11-16 17:42
Hi @basilfx,

Your script don't manages "id" well. However, (`offer_has_country.country_id`) size (TINYINT) is well detected but not `country.id`.

SQL (MariaDB 10.1) dump part:

```sql
CREATE TABLE `country` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `code` char(2) DEFAULT NULL,
  `code3` char(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  UNIQUE KEY `code_UNIQUE` (`code`),
  UNIQUE KEY `code3_UNIQUE` (`code3`)
) ENGINE=InnoDB AUTO_INCREMENT=251 DEFAULT CHARSET=latin1;

CREATE TABLE `offer_has_country` (
  `offer_id` smallint(5) unsigned NOT NULL,
  `country_id` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`offer_id`,`country_id`),
  KEY `fk_country_has_offer_offer1_idx` (`offer_id`),
  KEY `fk_country_has_offer_country1_idx` (`country_id`),
  CONSTRAINT `fk_country_has_offer_country1` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_has_offer_offer1` FOREIGN KEY (`offer_id`) REFERENCES `offer` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

It generates:

```php
$this->table('country', array())
    ->addColumn('name', 'string', array('length' => 60))
    ->addColumn('code', 'char', array('length' => 2, 'null' => true))
    ->addColumn('code3', 'char', array('length' => 3, 'null' => true))
    ->create();

$this->table('offer_has_country', array('id' => false, 'primary_key' => array('offer_id', 'country_id')))
    ->addColumn('offer_id', 'integer', array('length' => 65535))
    ->addColumn('country_id', 'integer', array('length' => 255))
    ->create();
```

**Comment by jwh315** [comment] 2016-11-17 03:18
@HanXHX I noticed this as well. I am wondering if it would be better to explicitly define the primary key even when the primary key is `id`

```
$this->table('country', [ 'id' => false, 'primary_key' => [ 'id' ] ])
             ->addColumn('id', 'integer', [ 'length' => 255 ])
             ->addColumn('name', 'string', [ 'length' => 60, 'collation' => 'latin1_swedish_ci' ])
             ->addColumn('code', 'char', [ 'length' => 2, 'null' => true, 'collation' => 'latin1_swedish_ci' ])
             ->addColumn('code3', 'char', [ 'length' => 3, 'null' => true, 'collation' => 'latin1_swedish_ci' ])
             ->addIndex([ 'name' ], [ 'name' => 'name_UNIQUE', 'unique' => true ])
             ->addIndex([ 'code' ], [ 'name' => 'code_UNIQUE', 'unique' => true ])
             ->addIndex([ 'code3' ], [ 'name' => 'code3_UNIQUE', 'unique' => true ])
             ->create();
```

This seems to work correctly. @basilfx, I could implement this if you think it is a good idea.

**Comment by HanXHX** [comment] 2016-11-17 08:10
Hi @jwh315, @basilfx,

I think more verbose output is less debug ;)

**Comment by basilfx** [comment] 2016-11-17 09:27
> This seems to work correctly. @basilfx, I could implement this if you think it is a good idea.

@jwh315 That is fine with me as long as Phinx supports that concept. I want to avoid API/syntax changes to Phinx where possible :-)

**Comment by micheleangioni** [comment] 2017-01-27 09:23
Hi @robmorgan , 
any chance to see such a feature implemented in (original) Phinx?

**Comment by Maelstromeous** [comment] 2017-01-30 22:40
Hey @robmorgan, this is literally all that Phinx is missing for me... any chance to revive this very old feature request? :)

**Comment by odan** [comment] 2017-01-31 06:35
I couldn't wait longer and implemented a phinx migrations generator for MySQL (only). It's still beta and I'm looking for feedback.
https://github.com/odan/phinx-migrations-generator

**Comment by glensc** [comment] 2017-04-27 19:35
@basilfx basilfx/0.7.x-dev (d70750f) creates invalid php syntax:

```
->addIndex(array('cam_prj_id', 'cam_customer_id', 'cam_usr_id'), 'unique' => true )
```

mysqldump line for that key:
```
  UNIQUE KEY `cam_manager` (`cam_prj_id`,`cam_customer_id`,`cam_usr_id`),
```

**Comment by bmudda** [comment] 2018-02-05 20:56
Is there a plan to integrate this to the Phinx project? This would be really helpful when using Phinx in an already existing project with existing schema.

**Comment by aat2703** [comment] 2018-09-19 14:35
Any progress on this issue? I think its a major issue for Phinx... Most people using Phinx already have mature applications running... And hand writing several hundreds of table migrations manually is insane... Also a diff generator would be helpful too

**Comment by broberts-mrmc** [comment] 2018-09-19 14:48
For what it’s worth, we use Phinx [for migrations], but as you stated, we also found it to lack a “diff” capability, unlike Doctrine, for example, which takes a diffident, ORM-coupled approach that makes “diffing” less problematic for the framework.

While we haven’t adopted the whole of the framework, we’ve found CakePHP includes a diff utility for generating a [Phinx] migration from an existing database. CakePHP and Phinx are integrate via its migrations plugin.

We’ve used Cake for this purpose with success though we’ve found these generated migrations to need some TLC, though it’s still much better that writing them from scratch.

I hope this helps.

On Sep 19, 2018, at 9:35 AM, Andreas Aagaard <notifications@github.com<mailto:notifications@github.com>> wrote:

*External Email Message*

________________________________

Any progress on this issue? I think its a major issue for Phinx... Most people using Phinx already have mature applications running... And hand writing several hundreds of table migrations manually is insane... Also a diff generator would be helpful too

**Comment by aat2703** [comment] 2018-09-19 15:08
@broberts-mrmc thank you

I'll take a look at it - Seems like it would be the best solution atm. 

To help others in same situation: https://book.cakephp.org/3.0/en/migrations.html

**Comment by guilhermeaiolfi** [comment] 2019-01-23 15:34
It's been a while since @basilfx and @celorodovalho worked on it. It looked good and all, why it wasn't released in any stable version?

I started working with phinx today and that's a hell of a feature to save time and energy. It would improve a lot the workflow for me, at least. That and a diff command to create migrations for you automatically are the only features missing from phinx.

Thanks.

**Comment by othercorey** [comment] 2020-05-09 00:29
Closing due to lack of activity or out of scope. If there is new interest, please open a PR.

**Closed by othercorey** 2020-05-09 00:29 UTC
Labels: feature

**Comment by linc** [comment] 2025-09-23 14:49
Cake can do this, and will create a migration compatible with Phinx (as you'd guess).

1. Create a new Cake project: `composer create-project --prefer-dist cakephp/app:~4.0 some_folder`
2. Add the database creds in: `path_to/some_folder/config/app_local.php`
3. Run a Cake snapshot: `path_to/some_folder/bin/cake bake migration_snapshot SomeName`
4. Copy the new file created in `path_to/some_folder/config/Migrations` into your original project migrations folder.

While mildly annoying Phinx cannot do it natively, it's presumably a rare enough need (over the lifetime of a single project) that I wouldn't try to cram it in and simply use this workaround instead.
