### ISSUE TITLE
ability to run up/down alongside with change

### ISSUE THREAD

**Issue by steffkes** [cakephp/phinx#626] opened 2015-08-23 10:27 UTC
while working on a project that brought up #625 another thing is that i have to enable/disable an postgres extension while running the migration.

i'm not used to `change()` (didn't exist in the previous tools i've used) i've started figuring out what my migration actually needs to do and one thing it needs to do is enable an extension. which is absolutely easy using `execute` to issue a query.

reversing the migration fails because the extension is already enabled (obviously). extending the `CREATE EXTENSION` query with a `IF NOT EXISTS` would work, although i dislike that is does not actually disable the extension but only hide the underlying error it would generate.

Looking at `Migration\Manager\Environment#executeMigration` i see the following (compressed for brevity):

```
public function executeMigration(MigrationInterface $migration, $direction = MigrationInterface::UP)
{
    $direction = ($direction == MigrationInterface::UP) ? MigrationInterface::UP : MigrationInterface::DOWN;

    if (method_exists($migration, MigrationInterface::CHANGE)) {
        if ($direction == MigrationInterface::DOWN) {
            $migration->change();
            $proxyAdapter->executeInvertedCommands();
        } else {
            $migration->change();
        }
    } else {
        $migration->{$direction}();
    }
}
```

which goes either for `up`/`down` **or** `change` - which is in agreement with the documentation:

> Please be aware that when a `change` method exists Phinx will automatically ignore the `up` and `down` methods. If you need to use these methods it is recommended to create a separate migration file.

only that having another migration is not really fixing my problem.

to conclude the question/idea: enabling `up`/`down` to run alongside `change` might not be the best idea (given that it did not work that way until now and would be a BC) - i was thinking about a hook that would be executed (in case it exists) _before_ the migration is going up and _after_ the migration is going down.

any thoughts on that? or is there already something else that people are using and that i'm simply overlooking ;o

**Comment by alexbowers-tecmark** [comment] 2015-09-04 15:19
Why can't you just have up and down defined instead of change?

**Comment by steffkes** [comment] 2015-09-04 15:24
well, i can - but for which reason? the operations are exactly the opposite of each other, and that's exactly what `change` is meant to be for, isn't it?

**Comment by temperedvision** [comment] 2015-09-04 15:55
I am against this for one main reason. There would be no agreement on order of execution which would result in additional configuration for what would be a low used feature.

**Comment by steffkes** [comment] 2015-09-04 16:02
@temperedvision not sure how the following fails to be specific about it?

> ... i was thinking about a hook that would be executed (in case it exists) before the migration is going up and after the migration is going down.

seems pretty normal (in regards to migrations) to me. do something before we actually run, in case we go up (think of various preparations that need to be done before) and after we did run, in case we go down (think cleanup of some type). no?

and you don't have to use it .. if you're fine with whatever the migration does by itself .. no more work required, just ignore it (:

**Comment by alexbowers-tecmark** [comment] 2015-09-07 08:14
IF we go that far, should we not then have a before and after for both up and down. For various cleanups after up and down etc.

Also, these are not the exact opposite if you require a precursor and an effect afterwards.

**Comment by steffkes** [comment] 2015-09-07 08:43
I didn't need that much tooling around - but that shouldn't be an argument to not do it.

**Comment by mvrhov** [comment] 2016-02-10 17:47
I would also need something like that. 4 events two for up 2 for down. that are run alongside a change method.
The problem is that to use a phinx in somewhat more advanced form on postgresql database there are a lot of things that phinx doesn't support right now. Having those events would enable me to execute them instead of writing up/down for everything.

**Comment by mvrhov** [comment] 2017-02-02 13:41
@robmorgan: You just added feature here.. But didn't look at the PR I provided. Also this PR is another one that's almost a year old and it's still not merged. I'm seriously thinking of doing a "fork and run" as there is no responses from the developers with merge privileges.

**Comment by mh-ovos** [comment] 2017-09-11 18:41
@mvrhov i'd happily use your fork ;)

**Comment by lorenzo** [comment] 2017-09-13 11:47
@mvrhov Rob is no longer maintaining this project. I'm actually going to close this ticket as it is too old and long for me to spend time on it, but please make sure to open another explaining your need and I'll look at it right away.

**Closed by lorenzo** 2017-09-13 11:47 UTC
Labels: feature
