### ISSUE TITLE
Ability to point to php config by default

### ISSUE THREAD

**Issue by rbalik** [cakephp/phinx#526] opened 2015-03-23 22:20 UTC
It would be great if there was a config option that could go in phinx.yml to tell it to load a different config file by default. This would just allow for simplifying the migration commands for those of us using a PHP -based config file.

**Comment by dereuromark** [comment] 2017-10-08 16:41
Sounds like a duplicate of https://github.com/cakephp/phinx/issues/466

**Closed by dereuromark** 2017-10-08 16:41 UTC
