### ISSUE TITLE
Namespace loading failed

### ISSUE THREAD

**Issue by valetzyzy** [cakephp/phinx#756] opened 2016-01-19 12:20 UTC
When set namespace in migration file PHINX can't load file

``` php
<?php

namespace app\db\migrations;

use Phinx\Migration\AbstractMigration;

class CreateUserSettings extends AbstractMigration {}
```

Some Exception

``` php
  [InvalidArgumentException]                                                                                                              
  Could not find class "CreateUserSettings" in file "~/app/db/migrations/20160118105051_create_user_settings.php"

```

**Comment by rquadling** [comment] 2016-01-19 14:49
Migrations, at the moment, cannot be namespaced.

**Comment by shadowhand** [comment] 2016-01-23 16:50
See #168

**Comment by tariquesani** [comment] 2017-06-28 05:40
#1070 Pull request solves this issue, is mergeable and passes all tests
Duplicate of #168 ?

**Comment by lorenzo** [comment] 2017-06-28 08:11
closing as duplicate.

**Closed by lorenzo** 2017-06-28 08:11 UTC
Labels: bug
