### ISSUE TITLE
how to generate migrations from an existing database

### ISSUE THREAD

**Issue by angusty** [cakephp/phinx#820] opened 2016-04-13 09:10 UTC
how to generate migrations from an existing database, including indexes and foreign keys?

**Comment by jmbeekman** [comment] 2016-04-18 18:16
I'm working on a script to extend https://github.com/gwa/MySQL2Phinx in an attempt to fully cover MySQL, and then probably PostGREs

**Comment by odan** [comment] 2017-10-02 17:59
Hi! You could try to generate a migration with [odan/phinx-migrations-generator](https://github.com/odan/phinx-migrations-generator)

**Comment by yoX64** [comment] 2018-01-30 10:08
Great work, @odan! Thank you so much!

**Comment by dereuromark** [comment] 2018-01-30 10:24
You can link this in the docs maybe.

**Comment by delboy1978uk** [comment] 2019-01-21 11:56
this is just what i was looking for :-D Is it able to create inserts for the existing data in the database?

**Comment by dereuromark** [comment] 2020-04-11 06:25
Duplicate of https://github.com/cakephp/phinx/issues/350 ?

**Closed by dereuromark** 2020-04-11 06:25 UTC
Labels: docs
