### ISSUE TITLE
Duplicate migration has the same version as

### ISSUE THREAD

**Issue by timo002** [cakephp/phinx#1256] opened 2017-12-06 21:56 UTC
Hello,

I'm getting a error:
```
Duplicate migration - "/path/to/db/migrations/20160729121849_create_product_option_table.php" has the same version as "20160729121849"
```

I had installed phinx 0.6.2, I just updated to 0.9.1 and still have this problem. There really is no duplicate migration.

**Comment by chinpei215** [comment] 2017-12-07 17:39
What If you change
https://github.com/cakephp/phinx/blob/454238f901234d31152393f5cee6b7dfc708e9be/src/Phinx/Migration/Manager.php#L680
to
```php
$class = new \ReflectionClass($versions[$version]);
throw new \InvalidArgumentException(sprintf('Duplicate migration - "%s" has the same version as "%s"', $filePath,  $class->getFileName()));
```
?

I think you can see the file name that causes the exception.

**Comment by stormpat** [comment] 2017-12-15 10:07
Having the same issue. Not sure when this bug was introduced. I get errors in the projects first migration, originally built in 2014.

```
Duplicate migration - "<omitted>/migrations/20141222131514_omitted_table.php" has the same version as "20141222131514"
```

**Comment by chinpei215** [comment] 2017-12-20 05:58
@stormpat Thank you for the information.
@timo002 Would the above information help you? If this issue is caused by a bug of third-party, I would like to close this issue ticket.

**Comment by stormpat** [comment] 2017-12-20 07:52
One more thing, the latest High Sierra update (10.13.2) fixes the NFS issue. So no need for rsync!

**Comment by chinpei215** [comment] 2017-12-20 08:26
Thanks again.

**Closed** 2018-01-08 22:00 UTC

**Comment by ngarel** [comment] 2024-04-19 08:54
Still a bug on the latest version.
I made the migration files on mac. Pushed the files to a build machine (gitlab) deploys them as an artifacts.
I copied the files on Windows and run the migration command.  The same error is reported.
I tried renaming the files, updating them, nothing works.
