### ISSUE TITLE
MySQL Timestamp Precision

### ISSUE THREAD

**Issue by johnrobertporter** [cakephp/phinx#1301] opened 2018-02-09 17:02 UTC
The `timestamp `type in MySQL allows for precision values like `timestamp(4)`. Phinx seems unable to do this at present.

**Comment by dereuromark** [comment] 2018-03-01 20:38
Duplicate of https://github.com/cakephp/phinx/issues/1301 ?

**Comment by dereuromark** [comment] 2018-03-01 20:39
Are you able to provide a pull request here?

**Comment by johnrobertporter** [comment] 2018-03-14 15:54
Sadly not, I am under a lot of pressure to get too much work done. I would if I could.

Plus I don't know the internals of this code base and it looks very complicated.

**Closed** 2018-04-29 12:27 UTC
Labels: feature
